working_directory = "/Users/mikiyax/swallow/element/"

[colors.bright]
black = "#3E3859"
blue = "#65B2FF"
cyan = "#63F2F1"
green = "#A1EFD3"
magenta = "#D4BFFF"
red = "#ff757f"
white = "#ffffff"
yellow = "#FFE6B3"

[colors.cursor]
cursor = "#7aa2f7"
text = "#000000"

[colors.normal]
black = "#121212"
blue = "#7aa2f7"
cyan = "#91DDFF"
green = "#4fd6be"
magenta = "#A37ACC"
red = "#ff757f"
white = "#CDD6F4"
yellow = "#F9E2Af"

[colors.primary]
background = "#1e1d2d"
foreground = "#CDD6F4"

[colors.search.focused_match]
background = "#D8DEE9"
foreground = "#100E23"

[colors.search.matches]
background = "#ffffff"
foreground = "#000000"

[colors.selection]
background = "#ffffff"
text = "#000000"

[cursor]
blink_interval = 500
blink_timeout = 3
thickness = 0.2
unfocused_hollow = true
vi_mode_style = "Underline"

[cursor.style]
blinking = "On"
shape = "Underline"

[env]
TERM = "xterm-256color"

[font]
size = 16

[font.italic]
family = "Monofur Nerd Font"
style = "Italic"

[font.normal]
family = "Monofur Nerd Font"
style = "Regular"

[font.offset]
x = 1
y = 6

[[keyboard.bindings]]
chars = "\u0001M"
key = "M"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0001B"
key = "B"
mods = "Command"

[[keyboard.bindings]]
chars = """
\u001B:w
"""
key = "S"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0001$"
key = "R"
mods = "Command"

[[keyboard.bindings]]
chars = "dse"
key = "D"
mods = "Option"

[[keyboard.bindings]]
chars = "cse"
key = "C"
mods = "Option"

[[keyboard.bindings]]
chars = "\u0001c"
key = "T"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0001x"
key = "W"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0001d"
key = "D"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0001p"
key = "P"
mods = "Command"

[[keyboard.bindings]]
chars = "gc"
key = "Slash"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00011"
key = "Key1"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00012"
key = "Key2"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00013"
key = "Key3"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00014"
key = "Key4"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0001E"
key = "Key5"
mods = "Command"

[scrolling]
history = 2000

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

[window]
decorations = "buttonless"
dynamic_padding = false
opacity = 0.991
title = "Mikiya"

[window.dimensions]
columns = 200
lines = 70

[window.padding]
x = 6
y = 3

[window.position]
x = 50
y = 200
